server:
  port: 9000

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 20

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    open-in-view: false

aligo:
  user-id: ${ALIGO_USER_ID}
  api-key: ${ALIGO_API_KEY}
  sender: ${ALIGO_SENDER}
