CREATE TABLE IF NOT EXISTS body_photo
(
    body_photo_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id           BIGINT    NOT NULL,
    image_url           TEXT      NOT NULL,
    is_review_completed BOOLEAN   NOT NULL,
    created_at          TIMESTAMP NOT NULL,
    updated_at          TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_body_photo_member_id ON body_photo (member_id);