CREATE TABLE release_ui
(
    release_ui_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mobile_os     TEXT      NOT NULL,
    app_version   TEXT      NOT NULL,
    is_release    BOOLEAN   NOT NULL,
    created_at    TIMESTAMP NOT NULL,
    updated_at    TIMESTAMP
);

CREATE UNIQUE INDEX idx_release_ui_mobile_os_app_version ON release_ui(mobile_os, app_version);
