CREATE TABLE IF NOT EXISTS review_rotation_queue
(
    review_rotation_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    body_photo_id       BIGINT    NOT NULL UNIQUE,
    reviewed_member_ids JSONB,
    created_at          TIMESTAMP NOT NULL
);
