CREATE TABLE IF NOT EXISTS member_block_relation
(
    member_block_relation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id                BIGINT    NOT NULL,
    blocked_member_id        BIGINT    NOT NULL,
    created_at               TIMESTAMP NOT NULL,
    created_by               BIGINT    NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_member_block_relation_member_id_blocked_member_id
    ON member_block_relation (member_id, blocked_member_id);
