CREATE TABLE IF NOT EXISTS body_review
(
    body_review_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    body_photo_id  BIGINT    NOT NULL,
    member_id      BIGINT    NOT NULL,
    score          INT       NOT NULL,
    created_at     TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_body_review_body_photo_id ON body_review (body_photo_id);
